// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/proto/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_internal_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Left          float32                `protobuf:"fixed32,2,opt,name=left,proto3" json:"left,omitempty"`
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Right         float32                `protobuf:"fixed32,4,opt,name=right,proto3" json:"right,omitempty"`
	HasTask       bool                   `protobuf:"varint,5,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	ExprId        string                 `protobuf:"bytes,6,opt,name=expr_id,json=exprId,proto3" json:"expr_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_internal_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetLeft() float32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Task) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Task) GetRight() float32 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *Task) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *Task) GetExprId() string {
	if x != nil {
		return x.ExprId
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Result        float32                `protobuf:"fixed32,4,opt,name=result,proto3" json:"result,omitempty"`
	ExprId        string                 `protobuf:"bytes,5,opt,name=expr_id,json=exprId,proto3" json:"expr_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_internal_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskResult) GetExprId() string {
	if x != nil {
		return x.ExprId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_internal_proto_agent_proto protoreflect.FileDescriptor

const file_internal_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/agent.proto\x12\x05agent\")\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x99\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04left\x18\x02 \x01(\x02R\x04left\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12\x14\n" +
	"\x05right\x18\x04 \x01(\x02R\x05right\x12\x19\n" +
	"\bhas_task\x18\x05 \x01(\bR\ahasTask\x12\x17\n" +
	"\aexpr_id\x18\x06 \x01(\tR\x06exprId\"\x86\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x02R\x06result\x12\x17\n" +
	"\aexpr_id\x18\x05 \x01(\tR\x06exprId\"!\n" +
	"\x03Ack\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2o\n" +
	"\x13OrchestratorService\x12)\n" +
	"\aGetTask\x12\x11.agent.WorkerInfo\x1a\v.agent.Task\x12-\n" +
	"\fSubmitResult\x12\x11.agent.TaskResult\x1a\n" +
	".agent.AckB0Z.github.com/fstr52/final-calculator/proto/agentb\x06proto3"

var (
	file_internal_proto_agent_proto_rawDescOnce sync.Once
	file_internal_proto_agent_proto_rawDescData []byte
)

func file_internal_proto_agent_proto_rawDescGZIP() []byte {
	file_internal_proto_agent_proto_rawDescOnce.Do(func() {
		file_internal_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_agent_proto_rawDesc), len(file_internal_proto_agent_proto_rawDesc)))
	})
	return file_internal_proto_agent_proto_rawDescData
}

var file_internal_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_agent_proto_goTypes = []any{
	(*WorkerInfo)(nil), // 0: agent.WorkerInfo
	(*Task)(nil),       // 1: agent.Task
	(*TaskResult)(nil), // 2: agent.TaskResult
	(*Ack)(nil),        // 3: agent.Ack
}
var file_internal_proto_agent_proto_depIdxs = []int32{
	0, // 0: agent.OrchestratorService.GetTask:input_type -> agent.WorkerInfo
	2, // 1: agent.OrchestratorService.SubmitResult:input_type -> agent.TaskResult
	1, // 2: agent.OrchestratorService.GetTask:output_type -> agent.Task
	3, // 3: agent.OrchestratorService.SubmitResult:output_type -> agent.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_agent_proto_init() }
func file_internal_proto_agent_proto_init() {
	if File_internal_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_agent_proto_rawDesc), len(file_internal_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_agent_proto_goTypes,
		DependencyIndexes: file_internal_proto_agent_proto_depIdxs,
		MessageInfos:      file_internal_proto_agent_proto_msgTypes,
	}.Build()
	File_internal_proto_agent_proto = out.File
	file_internal_proto_agent_proto_goTypes = nil
	file_internal_proto_agent_proto_depIdxs = nil
}
